resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the camunda-operator itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- camundarelease_admin_role.yaml
- camundarelease_editor_role.yaml
- camundarelease_viewer_role.yaml
- databaseserverpreset_admin_role.yaml
- databaseserverpreset_editor_role.yaml
- databaseserverpreset_viewer_role.yaml
- databaseserver_admin_role.yaml
- databaseserver_editor_role.yaml
- databaseserver_viewer_role.yaml
- logicalrestorerdbms_admin_role.yaml
- logicalrestorerdbms_editor_role.yaml
- logicalrestorerdbms_viewer_role.yaml
- logicalrestoreelasticsearch_admin_role.yaml
- logicalrestoreelasticsearch_editor_role.yaml
- logicalrestoreelasticsearch_viewer_role.yaml
- logicalbackuprdbms_admin_role.yaml
- logicalbackuprdbms_editor_role.yaml
- logicalbackuprdbms_viewer_role.yaml
- managementauthconfig_admin_role.yaml
- managementauthconfig_editor_role.yaml
- managementauthconfig_viewer_role.yaml
- camundamanagementcluster_admin_role.yaml
- camundamanagementcluster_editor_role.yaml
- camundamanagementcluster_viewer_role.yaml
- camundaoptimize_admin_role.yaml
- camundaoptimize_editor_role.yaml
- camundaoptimize_viewer_role.yaml
- logicalbackupelasticsearch_admin_role.yaml
- logicalbackupelasticsearch_editor_role.yaml
- logicalbackupelasticsearch_viewer_role.yaml
- pointintimerestore_admin_role.yaml
- pointintimerestore_editor_role.yaml
- pointintimerestore_viewer_role.yaml
- backupschedule_admin_role.yaml
- backupschedule_editor_role.yaml
- backupschedule_viewer_role.yaml
- objectstorageconfig_admin_role.yaml
- objectstorageconfig_editor_role.yaml
- objectstorageconfig_viewer_role.yaml
- secondarystorageconfig_admin_role.yaml
- secondarystorageconfig_editor_role.yaml
- secondarystorageconfig_viewer_role.yaml
- databaseconfig_admin_role.yaml
- databaseconfig_editor_role.yaml
- databaseconfig_viewer_role.yaml
- databaseserverconfig_admin_role.yaml
- databaseserverconfig_editor_role.yaml
- databaseserverconfig_viewer_role.yaml
- database_admin_role.yaml
- database_editor_role.yaml
- database_viewer_role.yaml
- elasticsearchclusterpreset_admin_role.yaml
- elasticsearchclusterpreset_editor_role.yaml
- elasticsearchclusterpreset_viewer_role.yaml
- elasticsearchcluster_admin_role.yaml
- elasticsearchcluster_editor_role.yaml
- elasticsearchcluster_viewer_role.yaml
- camundaclusterpreset_admin_role.yaml
- camundaclusterpreset_editor_role.yaml
- camundaclusterpreset_viewer_role.yaml
- camundaplatformconfig_admin_role.yaml
- camundaplatformconfig_editor_role.yaml
- camundaplatformconfig_viewer_role.yaml
- camundacluster_admin_role.yaml
- camundacluster_editor_role.yaml
- camundacluster_viewer_role.yaml

