---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.camunda.io
  resources:
  - backupschedules
  - camundaclusters
  - camundamanagementclusters
  - camundaoptimizes
  - databaseconfigs
  - databases
  - elasticsearchclusters
  - logicalbackupelasticsearches
  - logicalbackuprdbmses
  - pvcautoresizes
  - secondarystorageconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.camunda.io
  resources:
  - backupschedules/finalizers
  - camundaclusters/finalizers
  - camundamanagementclusters/finalizers
  - camundaoptimizes/finalizers
  - databases/finalizers
  - elasticsearchclusters/finalizers
  - logicalbackupelasticsearches/finalizers
  - logicalbackuprdbmses/finalizers
  - pvcautoresizes/finalizers
  verbs:
  - update
- apiGroups:
  - core.camunda.io
  resources:
  - backupschedules/status
  - camundaclusters/status
  - camundamanagementclusters/status
  - camundaoptimizes/status
  - camundaplatformconfigs/status
  - databaseconfigs/status
  - databases/status
  - databaseserverconfigs/status
  - elasticsearchclusters/status
  - logicalbackupelasticsearches/status
  - logicalbackuprdbmses/status
  - managementauthconfigs/status
  - objectstorageconfigs/status
  - pvcautoresizes/status
  - secondarystorageconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.camunda.io
  resources:
  - camundaclusterpresets
  - camundaplatformconfigs
  - databaseserverconfigs
  - elasticsearchclusterpresets
  - managementauthconfigs
  - objectstorageconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.camunda.io
  resources:
  - logicalrestores
  - pointintimerestores
  verbs:
  - get
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
