apiVersion: core.camunda.io/v1
kind: SecondaryStorageConfig
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: secondarystorageconfig-sample
spec:
  type: elasticsearch
  elasticsearch:
    endpoint: "https://elasticsearchcluster-sample-es-http:9200"
    credentialsSecretRef:
      name: secondarystorageconfig-sample-credentials
      usernameKey: username
      passwordKey: password
