apiVersion: core.camunda.io/v1
kind: ElasticsearchClusterPreset
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: elasticsearchclusterpreset-sample
spec:
  cluster:
    version: "9.2.4"
    replicas: 3
    storageSize: "64Gi"
