apiVersion: core.camunda.io/v1
kind: CamundaOptimize
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: camundaoptimize-sample
spec:
  version: "8.9.0"
  managementAuthRef: "managementauthconfig-sample"
  clusterRef:
    name: camundacluster-sample
  webapp:
    replicas: 2
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  importer:
    replicas: 1
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
  monitoring:
    serviceMonitor:
      enabled: true
      labels:
        release: "prometheus"
