apiVersion: core.camunda.io/v1
kind: ObjectStorageConfig
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: objectstorageconfig-sample
spec:
  type: S3
  s3:
    bucketName: objectstorageconfig-sample-bucket
    region: eu-west-1
    auth:
      type: workloadIdentity
      workloadIdentity:
        roleArn: "arn:aws:iam::123456789012:role/objectstorageconfig-sample-role"
