apiVersion: core.camunda.io/v1
kind: DatabaseServerConfig
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseserverconfig-sample
spec:
  engine: postgres
  version: "17"
  host: "postgres.default.svc.cluster.local"
  port: 5432
  adminCredentialsSecretRef:
    name: databaseserverconfig-sample-admin-credentials
    namespace: default
    usernameKey: username
    passwordKey: password
