apiVersion: core.camunda.io/v1
kind: BackupSchedule
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupschedule-sample
spec:
  clusterRef:
    name: camundacluster-sample
  # Every night at 02:00 UTC.
  schedule: "0 2 * * *"
  retained:
    completed: 7
    failed: 3
