apiVersion: core.camunda.io/v1
kind: CamundaCluster
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: camundacluster-sample
spec:
  # TODO(user): Add fields here
