apiVersion: core.camunda.io/v1
kind: CamundaClusterPreset
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: camundaclusterpreset-sample
spec:
  # TODO(user): Add fields here
