apiVersion: core.camunda.io/v1
kind: ObjectStorageConfig
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
  name: objectstorageconfig-sample
spec:
  provider: aws
  type: S3
  bucketId: "arn:aws:s3:::objectstorageconfig-sample-bucket"
  bucketName: objectstorageconfig-sample-bucket
  accountId: "arn:aws:iam::123456789012:role/objectstorageconfig-sample-role"
