apiVersion: core.camunda.io/v1
kind: LogicalRestore
metadata:
  labels:
    app.kubernetes.io/name: camunda-operator
    app.kubernetes.io/managed-by: kustomize
    camunda.io/cluster: camundacluster-sample
  name: camundacluster-sample-restore
spec:
  backupRef:
    kind: LogicalBackupElasticsearch
    name: camundacluster-sample-backup
  targetClusterRef:
    name: camundacluster-sample
