## Append samples of your project ##
resources:
- core_v1_camundacluster.yaml
- core_v1_camundaplatformconfig.yaml
- core_v1_camundaclusterpreset.yaml
- core_v1_elasticsearchcluster.yaml
- core_v1_elasticsearchclusterpreset.yaml
- core_v1_database.yaml
- core_v1_databaseserverconfig.yaml
- core_v1_databaseconfig.yaml
- core_v1_secondarystorageconfig.yaml
- core_v1_objectstorageconfig.yaml
- core_v1_backupschedule.yaml
- core_v1_pointintimerestore.yaml
- core_v1_logicalbackupelasticsearch.yaml
- core_v1_camundaoptimize.yaml
- core_v1_camundamanagementcluster.yaml
- core_v1_managementauthconfig.yaml
- core_v1_logicalbackuprdbms.yaml
- core_v1_logicalrestoreelasticsearch.yaml
- core_v1_logicalrestorerdbms.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
