## Append samples of your project ##
resources:
- core_v1_camundacluster.yaml
- core_v1_camundaplatformconfig.yaml
- core_v1_camundaclusterpreset.yaml
- core_v1_elasticsearchcluster.yaml
- core_v1_elasticsearchclusterpreset.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
